### ISSUE TITLE
Date cell leads to cell type 'Custom format'

### ISSUE THREAD

**Issue by rivella50** [felixbuenemann/xlsxtream#32]
Hi,
what i'm missing is to set a cell's value to a Date/DateTime and define a custom format which leads to

- cell category 'Date' (and not 'Custom' which is the case at the moment)
- the date is shown in the defined format

Until now i used rubyXL, which allowed this approach for a Date cell:
```
c = workbook[0].add_cell(0,0)
c.set_number_format('dd.mm.yyyy')
c.change_contents(Date.today)
```
Is that possible here too?
Thanks a lot.

**Comment by felixbuenemann** [comment]
Currently xlsxtream has hardcoded date formats:

* `yyyy\-mm\-dd` for `Date`
* `yyyy\-mm\-dd hh:mm:ss` for `DateTime`

It would be possible to add an option to customize the Date and DateTime formats globally, for the whole workbook.

Would that fit your use-case?

**Comment by rivella50** [comment]
That would still be too general for me. What about having an option to set the date formats per sheet column. I have a project with several sheets where various date columns occur and they actually have different date formats (i know that's horrible but i cannot change it).
And again the cell category should be 'Date' and not 'Custom' or 'Standard' for such column cells.
Thank you for considering that.

**Comment by felixbuenemann** [comment]
Excel doesn't have a data type for dates, they are just numbers with a custom number format applied. It's possible that Excel displays the format as 'Date' if either the built-in stylesheet is used or a custom format that matches it.

However the built-in styles for dates vary between the OpenXML spec and Excel, so it's not advisable to use them.

Defining the format for each column would be possible by extending the options hash in the columns array, however that's much more involved than a global setting, since we need to generate a list of several styles with the different number formats in memory and serialize it into the stylesheet when writing the workbook.

It's not particularly hard to build, it just requires more code changes than the global setting.

**Comment by rivella50** [comment]
It's your project, i can just tell you that it wouldn't fit my needs at the moment since it behaves too general regarding the dates aspect.

**Comment by felixbuenemann** [comment]
I've looked into this issue and in order to add the feature we would need a relatively complete implementation of cell styles, which consists of number formats, fonts, fills, borders etc.

Since that requires way more time than I'm willing to invest, I'm going to close this issue.

If someone else wants to contribute custom font, number format, etc. per column I'd be willing to discuss, review and merge that feature, but I'm not going to build it myself for now.
