### ISSUE TITLE
Does it support data_validation and formulas?

### ISSUE THREAD

**Issue by gnumarcelo** [felixbuenemann/xlsxtream#35]
Hi, thanks for creating this gem.

Does your gem support `data validation` and `formula` in cells?
Sorry but I dind't find it in the Docs.

ps.: By data_validation I mean this: `https://github.com/randym/axlsx/blob/master/examples/data_validation.rb`

Cheers

**Comment by felixbuenemann** [comment]
No and it is not something I'm planning to add.

Xlsxstream is supposed to be a replacement for csv, since importing csv in Excel is usually error prone.

This gem does not try to be a fully featured Excel writer.

If axlsx is not fast enough for your use case and you don't mind c-exts, you could try the [fast_excel](https://github.com/Paxa/fast_excel) gem.
