### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by sandstrom** [felixbuenemann/xlsxtream#5]
Is there a way to export dates in XLSX without using a custom format?

*Example of custom format in image below (this screenshot is from Numbers in macOS).*

![avoid-date-xlsx](https://user-images.githubusercontent.com/122287/29667322-34f57026-88dc-11e7-999a-3cb3efd499b5.png)

***

If I understand things correctly the `1` or `2` value for the `s-attribute` in say `<c r="E2" s="2">` determines the style, and the two styles are defined [here](https://github.com/felixbuenemann/xlsxtream/blob/master/lib/xlsxtream/workbook.rb#L97-L98). Is that correct?

According to [this document from Microsoft](https://msdn.microsoft.com/en-us/library/aa203732(v=office.11).aspx) they will interpret `HH:MM:SS`, `YYYY-MM-DD` and `YYYY-MM-DDTHH:MM:SS` as times/dates automatically.

Would you be willing to add configuration/options to toggle this (i.e. go with plain, correctly formatted date/time string and let Excel infer)?

*Let me know if I've misunderstood things, perhaps there are considerations here that I'm not aware of. I'll admit I don't know too much about the XLSX-format.*

**Comment by felixbuenemann** [comment]
I'm on holiday, but Ruby Date and DateTime Objects should work.

**Comment by felixbuenemann** [comment]
@sandstrom Could you elaborate on what you are trying to achieve?

Xlsxtream currently supports `Date`, `Time` and `DateTime` Ruby objects, as shown in the "Usage" section of the README. Ruby doesn't have a built-in data type for expressing time of the day without a date, so that is currently not supported.

Are you suggesting to use pattern matching to detect time-of-day, date and date-time in plain text and apply the proper formatting rules if found?

**Comment by sandstrom** [comment]
In the dropdown in the print screen `Custom Format 1` is used, but there is already an option for `Date`. Ideally it would use `Date` (the built-in format) automatically.

**Comment by sandstrom** [comment]
This issue still exist, but I cannot offer an easy solution and it doesn't seem worthwhile to pursue one at the moment. So I'm closing this.
